[package]
name = "activities-scheduler-server"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = '...' # Platform-specific.
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
split-debuginfo = '...'  # Platform-specific.
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
warp = { version = "0.3.6" }
# data serilization library
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

# uuid 
uuid = { version = "1.6.1", features = ["v4"] }

# tracing
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# local
handle-errors = { path = "handle-errors" }

# config
clap = { version = "4.4.8", features = ["derive"] }
proc-macro2 = "1.0.71"
dotenv = { version = "0.15.0" }

# db
sqlx = { version = "0.7.3", features = [
  "runtime-tokio-rustls",
  "migrate",
  "postgres",
] }

# random
rand = { version = "0.8.5" }

# encryption
rust-argon2 = { version = "2.0.0" }
paseto = { version = "2.0.2" }
openssl-sys = "0.9.98"
openssl = { version = "0.10.62", features = ["vendored"] }

# time 
chrono = { version = "0.4.31" }
