[package]
name = "activities-scheduler-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
warp = "0.3.6"
# data serilization library
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

# uuid 
uuid = { version = "1.6.1", features = ["v4"] }

# tracing
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# local
handle-errors = { path = "handle-errors" }

# config
clap = { version = "4.4.8", features = ["derive"] }
config = { version = "0.13.4", features = ["toml"] }

# db
sqlx = { version = "0.7.3", features = [
  "runtime-tokio-rustls",
  "migrate",
  "postgres",
] }

# random
rand = { version = "0.8.5" }
rust-argon2 = { version = "2.0.0" }
